version: '3'

services:
  traefik:
    image: traefik
    command: -c /traefik.toml --logLevel=DEBUG
    ports:
      - "8085:80"
      - "8086:8080"
    networks:
      - traefik
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: emilevauge/whoami
    networks:
      - traefik
    labels:
      - "traefik.backend=whoami"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.localhost.com"

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=your-client-id
      - PROVIDERS_GOOGLE_CLIENT_SECRET=your-client-secret
      - SECRET=something-random
      - INSECURE_COOKIE=true
      - DOMAIN=yourcompany.com
    networks:
      - traefik

networks:
  traefik:
