apiVersion: v1
description: Helm Chart for Traefik Forward Auth
home: https://github.com/Umaaz/traefik-forward-auth

name: traefik-forward-auth
version: 2.1.0
appVersion: 2.1.0

sources:
  - https://github.com/Umaaz/traefik-forward-auth
icon: https://raw.githubusercontent.com/Umaaz/traefik-forward-auth/master/chart/traefik-forward-auth/treafik.logo.png
maintainers:
  - email: b.w.donnelly1@gmail.com
    name: Ben Donnelly